# Generated by Django 2.1.4 on 2019-03-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20190328_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(blank='True', null='True', upload_to='videos/'),
        ),
    ]
