# Generated by Django 2.1.4 on 2019-03-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20190328_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(default='default-thumbnail', upload_to='thumbnails/'),
        ),
    ]
