# Generated by Django 2.1.4 on 2019-03-28 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(default='default-thumbnail.jpg', upload_to='thumbnails/'),
        ),
    ]
